### ISSUE TITLE
Define and list all the modules of Plorist

### ISSUE THREAD

**Issue by ghost** [karyall/Plorist-Future#32]
The basic and not reviewed modules list of Plorist is as follow:
1. Dahsboard
2. Billing
   - Purchases Bills
   - Sales Bills
3. Ledger
   - Customers
   - Vendors (Suppliers)
   - Accounts
4. Expenses
5. Journal
6. Items
   - Purchased Items (Bought Items)
   - Sold Items
   - Items List
   - Companies & Types
   - Warehouses
7. Users

**Comment by mbrig-co** [comment]
Change the Ledger section to become without sub-sections mean only one major section ledger or accounts is enough so instead of having sub-sections for each type of accounts create accounts with different types like: Customer Account, Vendor/Supplier Account and General or Personal Account.

**Comment by mbrig-co** [comment]
First review and update of the modules list:

| \# | Core Module | Sub Modules |
| ----- | ----- | ----- |
| 1 | Dashboard | N/A |
| 2 | Billing | 2.1. Purchases Bills<br />2.2. Sales Bills |
| 3 | Ledger | N/A |
| 4 | Expenses | N/A |
| 5 | Journal | N/A |
| 6 | Items | 6.1. Purchases/Bought Items<br />6.2. Sold Items<br />6.3. Items List<br />6.4. Items Companies & Types<br />6.5. Warehouses |
| 7 | Users | N/A |

**Comment by mbrig-co** [comment]
`Journal` also must be removed because the `Journal` we included here is reality `Daily Journal` and the goal of using `Daily Journal` is just to track daily transactions records which can be possible in software environment automatically because when a Data Entry employee makes deals with customers so software itself will track all the financial, stocking and etc info and record them very exactly which we can use later to build a `Daily Journal` from by using it date and time info.
